# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Poole
tagline:             The Jekyll Butler
url:                 http://mutasdev.github.io/pooleMutasDev/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Markus Mutas
  url:               https://twitter.com/mutasDEV
  email:             markus@mutas.dev

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/mutasdev/poolemutasdev
